"""Embed public/fonts/*.woff2 into src/film/fontdata.ts as base64.

Renders register fonts from memory instead of fetching them: a font request that never
answered used to stall a render permanently at a random frame.

    python video/tools/embed_fonts.py
"""

import base64
import json
from pathlib import Path

VIDEO = Path(__file__).resolve().parents[1]


def main() -> None:
    faces = json.loads((VIDEO / "src" / "film" / "fonts.json").read_text(encoding="utf-8"))
    lines = [
        "// Generated by tools/embed_fonts.py: the site's fonts as base64, so rendering fetches nothing.",
        "export const FONT_DATA: { family: string; style: string; weight: string; b64: string }[] = [",
    ]
    for f in faces:
        b64 = base64.b64encode((VIDEO / "public" / f["file"]).read_bytes()).decode()
        lines.append(f'  {{ family: "{f["family"]}", style: "{f["style"]}", weight: "{f["weight"]}", b64: "{b64}" }},')
    lines.append("];")
    (VIDEO / "src" / "film" / "fontdata.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
